apiVersion: v1
kind: Service
metadata:
  name: fastapi-celery
spec:
  selector:
    app: fastapi-celery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
