apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-celery
  labels:
    app: fastapi-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-celery
  template:
    metadata:
      labels:
        app: fastapi-celery
    spec:
      containers:
        - name: rahulecr95
          image: rahuldocker95/fastapi-celery:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
