name: CI/CD for FastAPI deployment on EKS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: FAST_API_DEPLOYMENT

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Replace with your AWS region

    - name: Build and Push Docker Image
      run: |
        docker build -t rahuldocker95/fastapi-celery:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push rahuldocker95/fastapi-celery:latest

    - name: Tag Docker image
      run: |
        docker tag rahuldocker95/fastapi-celery:latest 185738856137.dkr.ecr.ap-south-1.amazonaws.com/rahulecr95/fastapi-celery:latest


    - name: Push Docker image to Amazon ECR
      run: |
        docker push 185738856137.dkr.ecr.ap-south-1.amazonaws.com/rahulecr95/fastapi-celery:latest
