name: Docker CI/CD

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 185738856137.dkr.ecr.ap-south-1.amazonaws.com/rahulecr95

    - name: Build Docker image
      run: |
        docker build -t rahulecr95:latest .
      working-directory: ./Dockerfile  # Set the path to your Dockerfile

    - name: Tag Docker image
      run: |
        docker tag rahulecr95:latest 185738856137.dkr.ecr.ap-south-1.amazonaws.com/rahulecr95:latest

    - name: Push Docker image to Amazon ECR
      run: |
        docker push 185738856137.dkr.ecr.ap-south-1.amazonaws.com/rahulecr95:latest
